language: node_js
node_js:
- '8'
- '10'
script:
- npm test
notifications:
  slack: thebigsurf:EjL4xVZdsZgFkQ8MaBYEjAkp
  email: false
deploy:
  provider: npm
  email: guy@thebigsurf.co.uk
  api_key:
    secure: DJRGKFl/fMFMpGd6P/2LkwWie0rS9brgkAj5GdeL6L9I7TtBlrBwg3xM/kjWRuUri8mVoVqd7ztuXyH4YVhkpPe254lHACM6w0UwZstqIy25WDNPh6ay6i7Yww06iDdzb2L7yFvxt2QF3J3C5iBVTVkGdm/i+G4cJsvYaxTM7d/rBVMVsEPGL9660YZoArqLiNKHtM+iqHnzfNQa1PtgaBNx92v6oRmHrs7HYfPSM9OdNpuYX2k1d/NbuSrtJh68nAxp6pKbhNDkaIR1bIxDwiBj3em2YEIlepgSC0mxT5gcknTiEvIfkHPjVG+Qv0DYF6Hsqym/NjN8WBA+ILLOzczGoJABRS4M5Dbr9vJMdDc8cayfXB7NOKVjuf9ChxkGkd0Ay3f+ncJIphBqFYzXPpzp+wRgEcux5f30ModekS54mvTUUUgrgJRurkrIFo2sd7rsbzG6jMnnHFl9X2T1rJeX5rue9R4tILKDwk5HZPq26XuxOZkfBhq5BoO9FSzrpjfytjzk1wcLBufZF3rNi0g5X0twR2rPZPJfuqHHJrfrmIH3GP/kKZCPS7IjH/oxxlqTnQ9YaAACaFFXK5+knGhTBIe4vhyyQ/8+m5+wSRsB7WRswKoidvT5Sz1/PeEZSUibtZuSo0omcvjEUkkt5RP/uPwQr9Ctn7Ze4+68HFQ=
  on:
    tags: true
    branch: master
    repo: theGC/html-webpack-inline-svg-plugin
  skip_cleanup: false
